language: node_js
node_js:
- '0.11'
addons:
  code_climate:
    repo_token: 757ed9af2195b942c348d9851dfcd4745ec05efab634efc002ea459411f0513f
before_script:
  - npm install -g codeclimate-test-reporter
after_script:
- codeclimate-test-reporter < coverage/lcov.info
deploy:
  provider: npm
  email: serveradmin@octoblu.com
  api_key:
  on:
    tags: true
    branches: true
